version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      # - python/load-cache
      - python/install-deps
      - run:
          name: setup
          command: |
            pip install -r requirements-test.txt
            pip install -e ./
            pip install torch>=1.6.0
      # - python/save-cache
      - run:
          name: Test
          command: |
            pytest -sv test

workflows:
  main:
    jobs:
      - build-and-test
