version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      # - python/load-cache
      # - python/install-deps
      - run:
          name: setup
          command: |
            virtualenv -p python3.7 .venv
            source .venv/bin/activate
            pip install torch==1.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            pip install .
            pip install -r requirements-test.txt
            sudo apt-get -y install cmake
      # - python/save-cache
      - run:
          name: Test
          command: |
            source .venv/bin/activate
            pytest -sv test
            bash test/test.sh
            flake8 . --count --exit-zero --statistics

workflows:
  main:
    jobs:
      - build-and-test
